/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SilevisSelect {
    }
    interface SilevisSelectOption {
    }
    interface SlotTest {
    }
}
declare global {
    interface HTMLSilevisSelectElement extends Components.SilevisSelect, HTMLStencilElement {
    }
    var HTMLSilevisSelectElement: {
        prototype: HTMLSilevisSelectElement;
        new (): HTMLSilevisSelectElement;
    };
    interface HTMLSilevisSelectOptionElement extends Components.SilevisSelectOption, HTMLStencilElement {
    }
    var HTMLSilevisSelectOptionElement: {
        prototype: HTMLSilevisSelectOptionElement;
        new (): HTMLSilevisSelectOptionElement;
    };
    interface HTMLSlotTestElement extends Components.SlotTest, HTMLStencilElement {
    }
    var HTMLSlotTestElement: {
        prototype: HTMLSlotTestElement;
        new (): HTMLSlotTestElement;
    };
    interface HTMLElementTagNameMap {
        "silevis-select": HTMLSilevisSelectElement;
        "silevis-select-option": HTMLSilevisSelectOptionElement;
        "slot-test": HTMLSlotTestElement;
    }
}
declare namespace LocalJSX {
    interface SilevisSelect {
    }
    interface SilevisSelectOption {
        "onSilevisSelectActivated"?: (event: CustomEvent<Object>) => void;
    }
    interface SlotTest {
    }
    interface IntrinsicElements {
        "silevis-select": SilevisSelect;
        "silevis-select-option": SilevisSelectOption;
        "slot-test": SlotTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "silevis-select": LocalJSX.SilevisSelect & JSXBase.HTMLAttributes<HTMLSilevisSelectElement>;
            "silevis-select-option": LocalJSX.SilevisSelectOption & JSXBase.HTMLAttributes<HTMLSilevisSelectOptionElement>;
            "slot-test": LocalJSX.SlotTest & JSXBase.HTMLAttributes<HTMLSlotTestElement>;
        }
    }
}
